# Generated by Django 4.2 on 2023-04-19 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DynamicPricingSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_enabled", models.BooleanField(default=True)),
                ("is_lead_days_based", models.BooleanField(default=True)),
                ("lead_day_window", models.SmallIntegerField(default=60)),
                ("is_weekday_based", models.BooleanField(default=True)),
                ("is_month_based", models.BooleanField(default=True)),
                ("is_season_based", models.BooleanField(default=True)),
                ("is_availability_based", models.BooleanField(default=True)),
                ("is_time_based", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="HotelGroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="WeekdayBasedRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "multiplier_factor",
                    models.DecimalField(decimal_places=2, default=1, max_digits=3),
                ),
                (
                    "weekday",
                    models.SmallIntegerField(
                        choices=[
                            (1, "Monday"),
                            (2, "Tuesday"),
                            (3, "Wednesday"),
                            (4, "Thursday"),
                            (5, "Friday"),
                            (6, "Saturday"),
                            (7, "Sunday"),
                        ]
                    ),
                ),
                (
                    "setting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="weekday_based_rules",
                        to="rms.dynamicpricingsetting",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TimeBasedTriggerRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trigger_time", models.TimeField()),
                (
                    "multiplier_factor",
                    models.DecimalField(decimal_places=2, default=1, max_digits=3),
                ),
                ("min_availability", models.SmallIntegerField()),
                ("max_availability", models.SmallIntegerField()),
                ("is_today", models.BooleanField()),
                ("is_tommorow", models.BooleanField()),
                ("is_active", models.BooleanField()),
                (
                    "setting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="time_based_trigger_rules",
                        to="rms.dynamicpricingsetting",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SeasonBasedRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "multiplier_factor",
                    models.DecimalField(decimal_places=2, default=1, max_digits=3),
                ),
                ("name", models.CharField(max_length=64)),
                ("start_month", models.SmallIntegerField()),
                ("start_day", models.SmallIntegerField()),
                ("end_month", models.SmallIntegerField()),
                ("end_day", models.SmallIntegerField()),
                (
                    "setting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="season_based_rules",
                        to="rms.dynamicpricingsetting",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MonthBasedRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "multiplier_factor",
                    models.DecimalField(decimal_places=2, default=1, max_digits=3),
                ),
                (
                    "month",
                    models.SmallIntegerField(
                        choices=[
                            (1, "January"),
                            (2, "February"),
                            (3, "March"),
                            (4, "April"),
                            (5, "May"),
                            (6, "June"),
                            (7, "July"),
                            (8, "August"),
                            (9, "September"),
                            (10, "October"),
                            (11, "November"),
                            (12, "December"),
                        ]
                    ),
                ),
                (
                    "setting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="month_based_rules",
                        to="rms.dynamicpricingsetting",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LeadDaysBasedRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lead_days", models.SmallIntegerField()),
                (
                    "multiplier_factor",
                    models.DecimalField(decimal_places=2, default=1, max_digits=3),
                ),
                (
                    "setting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lead_days_based_rules",
                        to="rms.dynamicpricingsetting",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dynamicpricingsetting",
            name="hotel_group",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="dynamic_pricing_setting",
                to="rms.hotelgroup",
            ),
        ),
        migrations.CreateModel(
            name="AvailabilityBasedTriggerRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("max_availability", models.SmallIntegerField()),
                (
                    "multiplier_factor",
                    models.DecimalField(decimal_places=2, default=1, max_digits=3),
                ),
                (
                    "setting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availability_based_trigger_rules",
                        to="rms.dynamicpricingsetting",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="weekdaybasedrule",
            index=models.Index(
                fields=["setting", "weekday"], name="rms_weekday_setting_ff9845_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="weekdaybasedrule",
            unique_together={("setting", "weekday")},
        ),
        migrations.AddIndex(
            model_name="seasonbasedrule",
            index=models.Index(
                fields=["setting", "name"], name="rms_seasonb_setting_f90047_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="seasonbasedrule",
            unique_together={("setting", "name")},
        ),
        migrations.AddIndex(
            model_name="monthbasedrule",
            index=models.Index(
                fields=["setting", "month"], name="rms_monthba_setting_2b1936_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="monthbasedrule",
            unique_together={("setting", "month")},
        ),
        migrations.AddIndex(
            model_name="leaddaysbasedrule",
            index=models.Index(
                fields=["setting", "lead_days"], name="rms_leadday_setting_b09fb4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="leaddaysbasedrule",
            unique_together={("setting", "lead_days")},
        ),
        migrations.AddIndex(
            model_name="availabilitybasedtriggerrule",
            index=models.Index(
                fields=["setting", "max_availability"],
                name="rms_availab_setting_284a36_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="availabilitybasedtriggerrule",
            unique_together={("setting", "max_availability")},
        ),
    ]
