# Generated by Django 4.2 on 2023-04-25 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="dynamicpricingsetting",
            name="is_up_to_date",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="leaddaysbasedrule",
            name="is_active",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="monthbasedrule",
            name="is_active",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="occupancybasedtriggerrule",
            name="is_active",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="seasonbasedrule",
            name="is_active",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="timebasedtriggerrule",
            name="is_active",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="weekdaybasedrule",
            name="is_active",
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
