# Generated by Django 4.2 on 2023-04-27 02:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("django_celery_beat", "0018_improve_crontab_helptext"),
        ("rms", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leaddaysbasedrule",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="monthbasedrule",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="occupancybasedtriggerrule",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="seasonbasedrule",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="timebasedtriggerrule",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="weekdaybasedrule",
            name="is_active",
        ),
        migrations.AlterField(
            model_name="dynamicpricingsetting",
            name="lead_day_window",
            field=models.PositiveSmallIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name="leaddaysbasedrule",
            name="lead_days",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="monthbasedrule",
            name="month",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "January"),
                    (2, "February"),
                    (3, "March"),
                    (4, "April"),
                    (5, "May"),
                    (6, "June"),
                    (7, "July"),
                    (8, "August"),
                    (9, "September"),
                    (10, "October"),
                    (11, "November"),
                    (12, "December"),
                ]
            ),
        ),
        migrations.AlterField(
            model_name="occupancybasedtriggerrule",
            name="min_occupancy",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="seasonbasedrule",
            name="end_day",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="seasonbasedrule",
            name="end_month",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="seasonbasedrule",
            name="start_day",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="seasonbasedrule",
            name="start_month",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="timebasedtriggerrule",
            name="day_ahead",
            field=models.PositiveSmallIntegerField(
                choices=[(0, "Today"), (1, "Tomorrow")], default=0
            ),
        ),
        migrations.AlterField(
            model_name="timebasedtriggerrule",
            name="max_occupancy",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="timebasedtriggerrule",
            name="min_occupancy",
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name="timebasedtriggerrule",
            name="periodic_task",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="time_based_trigger_rule",
                to="django_celery_beat.periodictask",
            ),
        ),
        migrations.AlterField(
            model_name="weekdaybasedrule",
            name="weekday",
            field=models.PositiveSmallIntegerField(
                choices=[
                    (1, "Monday"),
                    (2, "Tuesday"),
                    (3, "Wednesday"),
                    (4, "Thursday"),
                    (5, "Friday"),
                    (6, "Saturday"),
                    (7, "Sunday"),
                ]
            ),
        ),
    ]
