# Generated by Django 4.2 on 2023-05-10 17:33

import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
import django.contrib.postgres.operations
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("django_celery_beat", "0018_improve_crontab_helptext"),
        ("pms", "0001_initial"),
        ("rms", "0001_initial"),
    ]

    operations = [
        django.contrib.postgres.operations.BtreeGistExtension(),
        migrations.AddField(
            model_name="dynamicpricingsetting",
            name="default_base_rate",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="timebasedtriggerrule",
            name="periodic_task",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="time_based_trigger_rules",
                to="django_celery_beat.periodictask",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="timebasedtriggerrule",
            unique_together={("setting", "hour", "day_ahead", "min_occupancy")},
        ),
        migrations.CreateModel(
            name="RatePlanPercentageFactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("percentage_factor", models.SmallIntegerField(default=0)),
                (
                    "rate_plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="percentage_factor",
                        to="pms.rateplan",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="IntervalBaseRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                ("dates", django.contrib.postgres.fields.ranges.DateRangeField()),
                ("base_rate", models.PositiveIntegerField(default=0)),
                (
                    "setting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interval_base_rates",
                        to="rms.dynamicpricingsetting",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="timebasedtriggerrule",
            name="max_occupancy",
        ),
        migrations.RemoveField(
            model_name="timebasedtriggerrule",
            name="minute",
        ),
        migrations.AddConstraint(
            model_name="intervalbaserate",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[("dates", "&&"), ("setting", "=")],
                name="exclude_overlapping_interval_base_rates",
            ),
        ),
    ]
