# Generated by Django 4.2 on 2023-04-21 22:50

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("rms", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="timebasedtriggerrule",
            old_name="is_tommorow",
            new_name="is_tomorrow",
        ),
    ]
