# Generated by Django 4.2 on 2023-04-25 23:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rms", "0002_dynamicpricingsetting_is_up_to_date_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="leaddaysbasedrule",
            name="multiplier_factor",
        ),
        migrations.RemoveField(
            model_name="monthbasedrule",
            name="multiplier_factor",
        ),
        migrations.RemoveField(
            model_name="occupancybasedtriggerrule",
            name="multiplier_factor",
        ),
        migrations.RemoveField(
            model_name="seasonbasedrule",
            name="multiplier_factor",
        ),
        migrations.RemoveField(
            model_name="timebasedtriggerrule",
            name="multiplier_factor",
        ),
        migrations.RemoveField(
            model_name="weekdaybasedrule",
            name="multiplier_factor",
        ),
        migrations.AddField(
            model_name="leaddaysbasedrule",
            name="percentage_factor",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="monthbasedrule",
            name="percentage_factor",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="occupancybasedtriggerrule",
            name="percentage_factor",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="seasonbasedrule",
            name="percentage_factor",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="timebasedtriggerrule",
            name="percentage_factor",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="weekdaybasedrule",
            name="percentage_factor",
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="leaddaysbasedrule",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="monthbasedrule",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="occupancybasedtriggerrule",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="seasonbasedrule",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="timebasedtriggerrule",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="weekdaybasedrule",
            name="is_active",
            field=models.BooleanField(default=False),
        ),
    ]
