# Generated by Django 4.2 on 2023-04-24 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("rms", "0002_rename_is_tommorow_timebasedtriggerrule_is_tomorrow"),
    ]

    operations = [
        migrations.CreateModel(
            name="OccupancyBasedTriggerRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("min_occupancy", models.SmallIntegerField()),
                (
                    "increment_factor",
                    models.SmallIntegerField(blank=True, default=None, null=True),
                ),
                (
                    "multiplier_factor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        default=None,
                        max_digits=3,
                        null=True,
                    ),
                ),
                (
                    "setting",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="occupancy_based_trigger_rules",
                        to="rms.dynamicpricingsetting",
                    ),
                ),
            ],
        ),
        migrations.RenameField(
            model_name="timebasedtriggerrule",
            old_name="max_availability",
            new_name="max_occupancy",
        ),
        migrations.RenameField(
            model_name="timebasedtriggerrule",
            old_name="min_availability",
            new_name="min_occupancy",
        ),
        migrations.AlterField(
            model_name="timebasedtriggerrule",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.DeleteModel(
            name="AvailabilityBasedTriggerRule",
        ),
        migrations.AddIndex(
            model_name="occupancybasedtriggerrule",
            index=models.Index(
                fields=["setting", "min_occupancy"],
                name="rms_occupan_setting_c6d25e_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="occupancybasedtriggerrule",
            unique_together={("setting", "min_occupancy")},
        ),
    ]
