# Generated by Django 4.2 on 2023-04-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "rms",
            "0004_rename_is_availability_based_dynamicpricingsetting_is_occupancy_based_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="occupancybasedtriggerrule",
            name="increment_factor",
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
