# Generated by Django 4.2 on 2023-04-24 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rms", "0005_alter_occupancybasedtriggerrule_increment_factor"),
    ]

    operations = [
        migrations.AddField(
            model_name="leaddaysbasedrule",
            name="increment_factor",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name="monthbasedrule",
            name="increment_factor",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name="seasonbasedrule",
            name="increment_factor",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name="timebasedtriggerrule",
            name="increment_factor",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name="weekdaybasedrule",
            name="increment_factor",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name="occupancybasedtriggerrule",
            name="increment_factor",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name="occupancybasedtriggerrule",
            name="multiplier_factor",
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
        ),
    ]
