# Generated by Django 4.2 on 2023-04-24 17:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("rms", "0006_leaddaysbasedrule_increment_factor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaddaysbasedrule",
            name="increment_factor",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="monthbasedrule",
            name="increment_factor",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="occupancybasedtriggerrule",
            name="increment_factor",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="seasonbasedrule",
            name="increment_factor",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="timebasedtriggerrule",
            name="increment_factor",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="weekdaybasedrule",
            name="increment_factor",
            field=models.IntegerField(default=0),
        ),
    ]
