# Generated by Django 4.2 on 2023-05-10 20:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("pms", "0002_remove_hotelapikey_hotel_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CMHotel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "cm",
                    models.CharField(
                        blank=True,
                        choices=[(None, "default"), ("CHANNEX", "Channex")],
                        max_length=16,
                    ),
                ),
                ("cm_id", models.UUIDField(blank=True, null=True)),
                ("cm_api_key", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "hotel",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_management",
                        to="pms.hotel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HotelAPIKey",
            fields=[
                (
                    "id",
                    models.CharField(
                        editable=False,
                        max_length=150,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("prefix", models.CharField(editable=False, max_length=8, unique=True)),
                ("hashed_key", models.CharField(editable=False, max_length=150)),
                ("created", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "name",
                    models.CharField(
                        default=None,
                        help_text="A free-form name for the API key. Need not be unique. 50 characters max.",
                        max_length=50,
                    ),
                ),
                (
                    "revoked",
                    models.BooleanField(
                        blank=True,
                        default=False,
                        help_text="If the API key is revoked, clients cannot use it anymore. (This cannot be undone.)",
                    ),
                ),
                (
                    "expiry_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="Once API key expires, clients cannot use it anymore.",
                        null=True,
                        verbose_name="Expires",
                    ),
                ),
                (
                    "hotel",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="api_key",
                        to="cm.cmhotel",
                    ),
                ),
            ],
            options={
                "verbose_name": "API key",
                "verbose_name_plural": "API keys",
                "ordering": ("-created",),
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CMRoomType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cm_id", models.UUIDField(blank=True, null=True)),
                (
                    "room_type",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_management",
                        to="pms.roomtype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CMRatePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cm_id", models.UUIDField(blank=True, null=True)),
                (
                    "rate_plan",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_management",
                        to="pms.rateplan",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="cmroomtype",
            constraint=models.UniqueConstraint(
                fields=("room_type", "cm_id"),
                name="unique_cm_id_per_room_type",
                violation_error_message="Room type with this external ID already exists",
            ),
        ),
        migrations.AddConstraint(
            model_name="cmrateplan",
            constraint=models.UniqueConstraint(
                fields=("rate_plan", "cm_id"),
                name="unique_cm_id_per_rate_plan",
                violation_error_message="Rate plan with this external ID already exists",
            ),
        ),
        migrations.AddConstraint(
            model_name="cmhotel",
            constraint=models.UniqueConstraint(
                fields=("cm", "cm_id"),
                name="unique_cm_id_per_cm",
                violation_error_message="Property with this external ID already exists",
            ),
        ),
    ]
