# Generated by Django 4.2 on 2023-04-18 15:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pms", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roomtype",
            name="base_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
