# Generated by Django 4.2 on 2023-04-28 15:05

from django.db import migrations, models
import timezone_field.fields


class Migration(migrations.Migration):
    dependencies = [
        ("pms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotel",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="hotel",
            name="city",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name="hotel",
            name="country",
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name="hotel",
            name="currency",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name="hotel",
            name="timezone",
            field=timezone_field.fields.TimeZoneField(default="UTC", use_pytz=False),
        ),
    ]
