# Generated by Django 4.2 on 2023-04-20 02:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pms", "0002_remove_rateplanrestrictions_availability_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="rate",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="rateplanrestrictions",
            name="rate",
            field=models.IntegerField(),
        ),
    ]
