# Generated by Django 4.0.10 on 2023-04-06 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('manager', 'Manager'), ('staff', 'Staff'), ('receptionist', 'Receptionist'), ('guest', 'Guest')], default='guest', max_length=16, verbose_name='Role'),
        ),
    ]
